export const RESOURCE_TYPE_OPTIONS = [
  { label: 'Audiovisual', value: 'audiovisual' },
  { label: 'Book', value: 'book' },
  { label: 'Book Chapter', value: 'book-chapter' },
  { label: 'Collection', value: 'collection' },
  { label: 'Computational Notebook', value: 'computational-notebook' },
  { label: 'Conference Paper', value: 'conference-paper' },
  { label: 'Conference Proceeding', value: 'conference-proceeding' },
  { label: 'Data Paper', value: 'data-paper' },
  { label: 'Dataset', value: 'dataset' },
  { label: 'Dissertation', value: 'dissertation' },
  { label: 'Event', value: 'event' },
  { label: 'Image', value: 'image' },
  { label: 'Interactive Resource', value: 'interactive-resource' },
  { label: 'Journal Article', value: 'journal-article' },
  { label: 'Model', value: 'model' },
  { label: 'Output Management Plan', value: 'output-management-plan' },
  { label: 'Peer Review', value: 'peer-review' },
  { label: 'Physical Object', value: 'physical-object' },
  { label: 'Preprint', value: 'preprint' },
  { label: 'Report', value: 'report' },
  { label: 'Service', value: 'service' },
  { label: 'Software', value: 'software' },
  { label: 'Sound', value: 'sound' },
  { label: 'Standard', value: 'standard' },
  { label: 'Text', value: 'text' },
  { label: 'Thesis', value: 'thesis' },
  { label: 'Workflow', value: 'workflow' },
  { label: 'Other', value: 'other' },
];
