// `value` must be from resourceTypeGeneral controlled vocab in https://schema.datacite.org/meta/kernel-4/
// see https://datacite-metadata-schema.readthedocs.io/en/4.6/appendices/appendix-1/resourceTypeGeneral/
export const RESOURCE_TYPE_OPTIONS = [
  { label: 'Audiovisual', value: 'Audiovisual' },
  { label: 'Book', value: 'Book' },
  { label: 'Book Chapter', value: 'BookChapter' },
  { label: 'Collection', value: 'Collection' },
  { label: 'Computational Notebook', value: 'ComputationalNotebook' },
  { label: 'Conference Paper', value: 'ConferencePaper' },
  { label: 'Conference Proceeding', value: 'ConferenceProceeding' },
  { label: 'Data Paper', value: 'DataPaper' },
  { label: 'Dataset', value: 'Dataset' },
  { label: 'Dissertation', value: 'Dissertation' },
  { label: 'Event', value: 'Event' },
  { label: 'Image', value: 'Image' },
  { label: 'Instrument', value: 'Instrument' },
  { label: 'Interactive Resource', value: 'InteractiveResource' },
  { label: 'Journal', value: 'Journal' },
  { label: 'Journal Article', value: 'JournalArticle' },
  { label: 'Model', value: 'Model' },
  { label: 'Output Management Plan', value: 'OutputManagementPlan' },
  { label: 'Peer Review', value: 'PeerReview' },
  { label: 'Physical Object', value: 'PhysicalObject' },
  { label: 'Preprint', value: 'Preprint' },
  { label: 'Project', value: 'Project' },
  { label: 'Report', value: 'Report' },
  { label: 'Service', value: 'Service' },
  { label: 'Software', value: 'Software' },
  { label: 'Sound', value: 'Sound' },
  { label: 'Standard', value: 'Standard' },
  { label: 'StudyRegistration', value: 'StudyRegistration' },
  { label: 'Text', value: 'Text' },
  { label: 'Workflow', value: 'Workflow' },
  { label: 'Other', value: 'Other' },
];
