module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  globalSetup: '<rootDir>/jest.global-setup.ts',
  collectCoverage: true,
  coverageReporters: ['json-summary', 'lcov', 'clover'],
  moduleNameMapper: {
    '^@osf/(.*)$': '<rootDir>/src/app/$1',
    '^@core/(.*)$': '<rootDir>/src/app/core/$1',
    '^@shared/(.*)$': '<rootDir>/src/app/shared/$1',
    '^@styles/(.*)$': '<rootDir>/assets/styles/$1',
    '^src/environments/environment$': '<rootDir>/src/environments/environment.ts',
  },
  transform: {
    '^.+\\.(ts|mjs|js|html)$': [
      'jest-preset-angular',
      {
        tsconfig: '<rootDir>/tsconfig.spec.json',
        stringifyContentPathRegex: '\\.(html|svg)$',
        useESM: true,
      },
    ],
  },
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$|@ngxs|@angular|@ngrx|parse5|entities|chart.js)'],
  testEnvironment: 'jsdom',
  moduleFileExtensions: ['ts', 'js', 'html', 'json', 'mjs'],
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'src/app/**/*.{ts,js}',
    '!src/app/app.config.ts',
    '!src/app/**/*.routes.{ts.js}',
    '!src/app/**/*.models.{ts.js}',
    '!src/app/**/*.model.{ts.js}',
    '!src/app/**/*.route.{ts,js}',
    '!src/app/**/*.spec.{ts,js}',
    '!src/app/**/*.module.ts',
    '!src/app/**/index.ts',
    '!src/app/**/public-api.ts',
  ],
  extensionsToTreatAsEsm: ['.ts'],
  coverageThreshold: {
    global: {
      branches: 14.15,
      functions: 14.83,
      lines: 41.15,
      statements: 41.63,
    },
  },
  testPathIgnorePatterns: [
    '<rootDir>/src/app/app.config.ts',
    '<rootDir>/src/app/app.routes.ts',
    '<rootDir>/src/app/features/registry/',
    '<rootDir>/src/app/features/project/',
    '<rootDir>/src/app/features/registries/',
    '<rootDir>/src/app/features/settings/addons/',
    '<rootDir>/src/app/features/settings/settings-container.component.ts',
    '<rootDir>/src/app/features/settings/tokens/components/',
    '<rootDir>/src/app/features/settings/tokens/mappers/',
    '<rootDir>/src/app/features/settings/tokens/store/',
    '<rootDir>/src/app/features/settings/tokens/pages/tokens-list/',
    '<rootDir>/src/app/shared/components/education-history/',
    '<rootDir>/src/app/shared/components/education-history-dialog/',
    '<rootDir>/src/app/shared/components/employment-history/',
    '<rootDir>/src/app/shared/components/employment-history-dialog/',
    '<rootDir>/src/app/shared/components/file-menu/',
    '<rootDir>/src/app/shared/components/files-tree/',
    '<rootDir>/src/app/shared/components/filter-chips/',
    '<rootDir>/src/app/shared/components/form-select/',
    '<rootDir>/src/app/shared/components/full-screen-loader/',
    '<rootDir>/src/app/shared/components/generic-filter/',
    '<rootDir>/src/app/shared/components/icon/',
    '<rootDir>/src/app/shared/components/info-icon/',
    '<rootDir>/src/app/shared/components/license/',
    '<rootDir>/src/app/shared/components/line-chart/',
    '<rootDir>/src/app/shared/components/list-info-shortener/',
    '<rootDir>/src/app/shared/components/loading-spinner/',
    '<rootDir>/src/app/shared/components/make-decision-dialog/',
    '<rootDir>/src/app/shared/components/markdown/',
    '<rootDir>/src/app/shared/components/password-input-hint/',
    '<rootDir>/src/app/shared/components/pie-chart/',
    '<rootDir>/src/app/shared/components/readonly-input/',
    '<rootDir>/src/app/shared/components/registration-card/',
    '<rootDir>/src/app/shared/components/resource-card/',
    '<rootDir>/src/app/shared/components/resource-citations/',
    '<rootDir>/src/app/shared/components/resource-metadata/',
    '<rootDir>/src/app/shared/components/reusable-filter/',
    '<rootDir>/src/app/shared/components/search-help-tutorial/',
    '<rootDir>/src/app/shared/components/search-input/',
    '<rootDir>/src/app/shared/components/search-results-container/',
    '<rootDir>/src/app/shared/components/select/',
    '<rootDir>/src/app/shared/components/shared-metadata/',
    '<rootDir>/src/app/shared/components/statistic-card/',
    '<rootDir>/src/app/shared/components/status-badge/',
    '<rootDir>/src/app/shared/components/stepper/',
    '<rootDir>/src/app/shared/components/sub-header/',
    '<rootDir>/src/app/shared/components/subjects/',
    '<rootDir>/src/app/shared/components/tags-input/',
    '<rootDir>/src/app/shared/components/text-input/',
    '<rootDir>/src/app/shared/components/toast/',
    '<rootDir>/src/app/shared/components/truncated-text/',
    '<rootDir>/src/app/shared/components/view-only-table/',
    '<rootDir>/src/app/shared/components/wiki/',
  ],
};
