module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  globalSetup: '<rootDir>/jest.global-setup.ts',
  collectCoverage: false,
  coverageReporters: ['json-summary', 'lcov', 'clover'],
  moduleNameMapper: {
    '^@osf/(.*)$': '<rootDir>/src/app/$1',
    '^@core/(.*)$': '<rootDir>/src/app/core/$1',
    '^@shared/(.*)$': '<rootDir>/src/app/shared/$1',
    '^@styles/(.*)$': '<rootDir>/assets/styles/$1',
    '^@testing/(.*)$': '<rootDir>/src/testing/$1',
    '^src/environments/environment$': '<rootDir>/src/environments/environment.ts',
  },
  transform: {
    '^.+\\.(ts|mjs|js|html)$': [
      'jest-preset-angular',
      {
        tsconfig: '<rootDir>/tsconfig.spec.json',
        stringifyContentPathRegex: '\\.(html|svg)$',
        useESM: true,
      },
    ],
  },
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$|@ngxs|@angular|@ngrx|parse5|entities|chart.js)'],
  testEnvironment: 'jsdom',
  moduleFileExtensions: ['ts', 'js', 'html', 'json', 'mjs'],
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'src/app/**/*.{ts,js}',
    '!src/app/app.config.ts',
    '!src/app/**/*.routes.{ts.js}',
    '!src/app/**/*.models.{ts.js}',
    '!src/app/**/*.model.{ts.js}',
    '!src/app/**/*.route.{ts,js}',
    '!src/app/**/*.enum.{ts,js}',
    '!src/app/**/*.type.{ts,js}',
    '!src/app/**/*.enum.{ts,js}',
    '!src/app/**/*.type.{ts,js}',
    '!src/app/**/*.spec.{ts,js}',
    '!src/app/**/*.module.ts',
    '!src/app/**/index.ts',
    '!src/app/**/public-api.ts',
  ],
  extensionsToTreatAsEsm: ['.ts'],
  coverageThreshold: {
    global: {
      branches: 14.27,
      functions: 15.55,
      lines: 42.6,
      statements: 43.2,
    },
  },
  watchPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/dist/',
    '<rootDir>/coverage/',
    '<rootDir>/src/assets/',
    '<rootDir>/src/environments/',
    '<rootDir>/src/@types/',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/src/app/app.config.ts',
    '<rootDir>/src/app/app.routes.ts',
    '<rootDir>/src/app/features/files/components',
    '<rootDir>/src/app/features/files/pages/file-detail',
    '<rootDir>/src/app/features/preprints/',
    '<rootDir>/src/app/features/project/addons/',
    '<rootDir>/src/app/features/project/overview/',
    '<rootDir>/src/app/features/project/registrations',
    '<rootDir>/src/app/features/project/wiki',
    '<rootDir>/src/app/features/registries/',
    '<rootDir>/src/app/features/registry/',
    '<rootDir>/src/app/features/settings/addons/',
    '<rootDir>/src/app/features/settings/tokens/store/',
    '<rootDir>/src/app/shared/components/file-menu/',
    '<rootDir>/src/app/shared/components/files-tree/',
    '<rootDir>/src/app/shared/components/line-chart/',
    '<rootDir>/src/app/shared/components/make-decision-dialog/',
    '<rootDir>/src/app/shared/components/pie-chart/',
    '<rootDir>/src/app/shared/components/resource-citations/',
    '<rootDir>/src/app/shared/components/reusable-filter/',
    '<rootDir>/src/app/shared/components/wiki/edit-section/',
    '<rootDir>/src/app/shared/components/wiki/wiki-list/',
  ],
};
