export const SEARCH_RESULT_CARDS_DATA = [
  {
    id: '1',
    title: 'Pseudo-Random Sonications For Brain HIFU',
    description:
      'While transcranial high intensity focused ultrasound is used in clinics for treating essential tremor and proposed for many other brain disorders, this promising treatment modality requires high energy resulting eventually in undesired transcranial high intensity focused ultrasound is used in clinics for treating essential tremor and proposed for many other brain disorders, this promising treatment modality requires high energy resulting eventually in undesired ',
    dateCreated: new Date('2019-01-28'),
    dateModified: new Date('2019-01-28'),
    category: 'Research',
    contributors: [
      { id: '1', name: 'Lin Wang' },
      { id: '2', name: 'Roman Nastyuk' },
    ],
    programArea: 'Technica',
    status: 'Completed',
    collectedType: '',
    dataType: '',
    disease: '',
    gradeLevels: '',
    issue: '',
    reviewsState: '',
    schoolType: '',
    studyDesign: '',
    volume: '',
  },
  {
    id: '2',
    title: 'Simulation Of Transcranial FUS Propagation',
    description:
      "While transcranial high intensity focused ultrasound is used in clinics for treating essential tremor and proposed for many other brain disorders, there are currently no precise tools for patient's selection and treatment planning. in this project, focused ultrasound is used in clinics for treating essential tremor and proposed for many other brain disorders",
    dateCreated: new Date('2019-01-28'),
    dateModified: new Date('2019-01-28'),
    category: 'Research',
    contributors: [{ id: '1', name: 'Lin Wang' }],
    programArea: 'Technica',
    status: 'Active',
    collectedType: '',
    dataType: '',
    disease: '',
    gradeLevels: '',
    issue: '',
    reviewsState: '',
    schoolType: '',
    studyDesign: '',
    volume: '',
  },
  {
    id: '3',
    title: 'Sonications For Brain HIFU',
    description:
      'While transcranial high intensity focused ultrasound is used in clinics for treating essential tremor and proposed for many other brain disorders, this promising treatment modality requires high energy resulting eventually in undesired transcranial high intensity focused ultrasound is used in clinics for treating essential tremor and proposed for many other brain disorders, this promising treatment modality requires high energy resulting eventually in undesired ',
    dateCreated: new Date('2019-01-28'),
    dateModified: new Date('2019-01-28'),
    category: 'Research',
    contributors: [{ id: '2', name: 'Roman Nastyuk' }],
    programArea: 'Technica',
    status: 'Completed',
    collectedType: '',
    dataType: '',
    disease: '',
    gradeLevels: '',
    issue: '',
    reviewsState: '',
    schoolType: '',
    studyDesign: '',
    volume: '',
  },
];

export const PROGRAM_AREA_FILTERS_OPTIONS = [
  { label: 'Public Policy', value: 'Public Policy' },
  { label: 'Child Welfare', value: 'Child Welfare' },
  { label: 'Criminal Justice', value: 'Criminal Justice' },
  { label: 'Medicine', value: 'Medicine' },
  { label: 'Public Health', value: 'Public Health' },
  { label: 'Social Work', value: 'Social Work' },
  { label: 'Nursing', value: 'Nursing' },
  { label: 'Education', value: 'Education' },
  { label: 'Law & Jurisprudence', value: 'Law & Jurisprudence' },
  { label: 'N/A', value: 'N/A' },
];

export const COLLECTED_TYPE_FILTERS_OPTIONS = [
  { label: 'Experiments', value: 'Experiments' },
  { label: 'Interviews', value: 'Interviews' },
  { label: 'Grounded Theory', value: 'Grounded Theory' },
  { label: 'Action Research', value: 'Action Research' },
  { label: 'Case Studies', value: 'Case Studies' },
  { label: 'Direct Observation', value: 'Direct Observation' },
  { label: 'Document Analysis', value: 'Document Analysis' },
  { label: 'Interpretive Research', value: 'Interpretive Research' },
  { label: 'Participatory Action Research', value: 'Participatory Action Research' },
  { label: 'Event-Sampling', value: 'Event-Sampling' },
  { label: 'Surveys', value: 'Surveys' },
  { label: 'Quasi-Experiments', value: 'Quasi-Experiments' },
  { label: 'Ethnography', value: 'Ethnography' },
  { label: 'Social Network Analysis', value: 'Social Network Analysis' },
  { label: 'Critical Research Methods', value: 'Critical Research Methods' },
  { label: 'Design Research', value: 'Design Research' },
  { label: 'Discourse Analysis', value: 'Discourse Analysis' },
  { label: 'Research Synthesis', value: 'Research Synthesis' },
];
