export enum CredentialsFormat {
  OAUTH = 'OAUTH1A',
  OAUTH2 = 'OAUTH2',
  USERNAME_PASSWORD = 'USERNAME_PASSWORD',
  ACCESS_SECRET_KEYS = 'ACCESS_KEY_SECRET_KEY',
  REPO_TOKEN = 'PERSONAL_ACCESS_TOKEN',
  DATAVERSE_API_TOKEN = 'DATAVERSE_API_TOKEN',
}
