export const environment = {
  production: true,
  webUrl: 'https://staging4.osf.io',
  downloadUrl: 'https://staging4.osf.io/download',
  apiUrl: 'https://api.staging4.osf.io/v2',
  apiUrlV1: 'https://staging4.osf.io/api/v1',
  apiDomainUrl: 'https://api.staging4.osf.io',
  shareDomainUrl: 'https://staging-share.osf.io/trove',
  addonsApiUrl: 'https://addons.staging4.osf.io/v1',
  fileApiUrl: 'https://files.us.staging4.osf.io/v1',
  funderApiUrl: 'https://api.crossref.org/',
  addonsV1Url: 'https://addons.staging4.osf.io/v1',
  casUrl: 'https://accounts.staging4.osf.io',
  recaptchaSiteKey: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
  facebookAppId: '1022273774556662',
  supportEmail: 'support@osf.io',
  defaultProvider: 'osf',
};
