export const environment = {
  production: false,
  webUrl: 'http://localhost:5000',
  downloadUrl: 'http://localhost:5000/download',
  apiUrl: 'http://localhost:8000/v2',
  apiUrlV1: 'http://localhost:5000/api/v1',
  apiDomainUrl: 'http://localhost:8000',
  shareDomainUrl: 'https://localhost:8003/trove',
  addonsApiUrl: 'http://localhost:8004/v1',
  fileApiUrl: 'http://localhost:7777/v1',
  funderApiUrl: 'https://api.crossref.org/',
  addonsV1Url: 'http://localhost:8004/v1',
  casUrl: 'http://localhost:8080',
  recaptchaSiteKey: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
  twitterHandle: 'OSFramework',
  facebookAppId: '1022273774556662',
  supportEmail: 'support@osf.io',
  defaultProvider: 'osf',
  dataciteTrackerRepoId: null,
  dataciteTrackerAddress: 'https://analytics.datacite.org/api/metric',
};
