import { SocialLinksModel } from '../models';

export const SOCIAL_LINKS: SocialLinksModel[] = [
  {
    id: 1,
    label: 'settings.profileSettings.social.labels.researcherId',
    address: 'http://researchers.com/rid/',
    placeholder: 'x-xxxx-xxxx',
    key: 'researcherId',
    icon: 'researcherID.png',
  },
  {
    id: 2,
    label: 'settings.profileSettings.social.labels.linkedIn',
    address: 'https://linkedin.com/in/',
    placeholder: 'in/userID, profie/view?profileID, or pub/pubID',
    key: 'linkedIn',
    icon: 'linkedin.svg',
  },
  {
    id: 3,
    label: 'settings.profileSettings.social.labels.twitter',
    address: 'https://x.com/',
    placeholder: 'twitterhandle',
    key: 'twitter',
    icon: 'x.svg',
  },
  {
    id: 4,
    label: 'settings.profileSettings.social.labels.github',
    address: 'https://github.com/',
    placeholder: 'username',
    key: 'github',
    icon: 'github.svg',
  },
  {
    id: 5,
    label: 'settings.profileSettings.social.labels.impactStory',
    address: 'https://impactstory.org/u/',
    placeholder: 'profileID',
    key: 'impactStory',
    icon: 'impactStory.png',
  },
  {
    id: 6,
    label: 'settings.profileSettings.social.labels.scholar',
    address: 'http://scholar.google.com/citations?user=',
    placeholder: 'profileID',
    key: 'scholar',
    icon: 'scholar.svg',
  },
  {
    id: 7,
    label: 'settings.profileSettings.social.labels.researchGate',
    address: 'https://researchgate.net/profile/',
    placeholder: 'profileID',
    key: 'researchGate',
    icon: 'researchGate.svg',
  },
  {
    id: 8,
    label: 'settings.profileSettings.social.labels.baiduScholar',
    address: 'http://xueshu.baidu.com/scholarID/',
    placeholder: 'profileID',
    key: 'baiduScholar',
    icon: 'baiduScholar.png',
  },
  {
    id: 9,
    label: 'settings.profileSettings.social.labels.ssrn',
    address: 'http://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=',
    placeholder: 'profileID',
    key: 'ssrn',
    icon: 'ssrn.svg',
  },
  {
    id: 10,
    label: 'settings.profileSettings.social.labels.profileWebsites',
    address: '',
    placeholder: 'https://yourwebsite.com',
    key: 'profileWebsites',
    icon: 'globe.svg',
  },
  {
    id: 11,
    label: 'settings.profileSettings.social.labels.academia',
    address: 'https://',
    placeholder: 'institution',
    key: 'academiaInstitution',
    icon: 'academia.svg',
    linkedField: {
      key: 'academiaProfileID',
      label: 'settings.profileSettings.social.labels.academiaProfileId',
      placeholder: 'profileId',
      address: '.academia.edu/',
    },
  },
];
