import { MenuItem } from 'primeng/api';

export const AUTHENTICATED_MENU_ITEMS: string[] = [
  'my-profile',
  'my-resources',
  'my-registrations',
  'my-projects',
  'my-preprints',
  'registries-overview',
  'settings',
];

export const PROJECT_MENU_ITEMS: MenuItem[] = [
  {
    id: 'project-overview',
    label: 'navigation.overview',
    routerLink: 'overview',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'project-metadata',
    label: 'navigation.metadata',
    routerLink: 'metadata',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'project-files',
    label: 'navigation.files',
    routerLink: 'files',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'project-wiki',
    label: 'navigation.wiki',
    routerLink: 'wiki',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'project-registrations',
    label: 'navigation.registrations',
    routerLink: 'registrations',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'project-contributors',
    label: 'navigation.contributors',
    routerLink: 'contributors',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'project-analytics',
    label: 'navigation.analytics',
    routerLink: 'analytics',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'project-addons',
    label: 'navigation.addons',
    routerLink: 'addons',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'project-settings',
    label: 'navigation.settings',
    routerLink: 'settings',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
];

export const PREPRINT_MENU_ITEMS: MenuItem[] = [
  {
    id: 'preprint-overview',
    label: 'navigation.overview',
    routerLink: 'overview',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
];

export const REGISTRATION_MENU_ITEMS: MenuItem[] = [
  {
    id: 'registration-overview',
    label: 'navigation.overview',
    routerLink: 'overview',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'registration-metadata',
    label: 'navigation.metadata',
    routerLink: 'metadata',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'registration-files',
    label: 'navigation.files',
    routerLink: 'files',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'registration-resources',
    label: 'navigation.resources',
    routerLink: 'resources',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'registration-wiki',
    label: 'navigation.wiki',
    routerLink: 'wiki',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'registration-components',
    label: 'navigation.components',
    routerLink: 'components',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'registration-contributors',
    label: 'navigation.contributors',
    routerLink: 'contributors',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'registration-links',
    label: 'navigation.links',
    routerLink: 'links',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
  {
    id: 'registration-analytics',
    label: 'navigation.analytics',
    routerLink: 'analytics',
    visible: true,
    routerLinkActiveOptions: { exact: true },
  },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'home',
    routerLink: '/',
    label: 'navigation.home',
    icon: 'osf-icon-home',
    routerLinkActiveOptions: { exact: true },
    visible: true,
  },
  {
    id: 'search',
    routerLink: '/search',
    label: 'navigation.searchOsf',
    icon: 'osf-icon-search',
    routerLinkActiveOptions: { exact: false },
    styleClass: 'mb-5',
    visible: true,
  },
  {
    id: 'my-resources',
    label: 'navigation.myResources',
    icon: 'osf-icon-my-projects',
    routerLinkActiveOptions: { exact: true },
    visible: false,
    items: [
      {
        id: 'my-projects',
        routerLink: '/my-projects',
        label: 'navigation.myProjects',
        routerLinkActiveOptions: { exact: false },
        visible: false,
      },
      {
        id: 'my-registrations',
        routerLink: '/my-registrations',
        label: 'navigation.registriesSubRoutes.myRegistrations',
        visible: false,
        routerLinkActiveOptions: { exact: true },
      },
      {
        id: 'my-preprints',
        routerLink: '/my-preprints',
        label: 'navigation.preprintsSubRoutes.myPreprints',
        visible: false,
        routerLinkActiveOptions: { exact: false },
      },
    ],
  },
  {
    id: 'projects',
    label: 'navigation.projects',
    icon: 'osf-icon-my-projects',
    routerLinkActiveOptions: { exact: true },
    visible: false,
    items: [
      {
        id: 'project-details',
        label: 'navigation.projectDetails',
        routerLink: null,
        visible: false,
        routerLinkActiveOptions: { exact: true },
        styleClass: 'border-none',
      },
    ],
  },
  {
    id: 'registries',
    label: 'navigation.registries',
    icon: 'osf-icon-registries',
    visible: true,
    routerLinkActiveOptions: { exact: true },
    items: [
      {
        id: 'registries-overview',
        routerLink: '/registries/overview',
        label: 'navigation.overview',
        visible: true,
        routerLinkActiveOptions: { exact: true },
      },
      {
        id: 'registries-moderation',
        routerLink: '/registries/osf/moderation',
        label: 'navigation.moderation',
        visible: false,
        routerLinkActiveOptions: { exact: true },
      },
      {
        id: 'registry-details',
        routerLink: null,
        label: 'navigation.registriesSubRoutes.registryDetails',
        visible: false,
        routerLinkActiveOptions: { exact: true },
        styleClass: 'border-none',
      },
    ],
  },
  {
    id: 'preprints',
    label: 'navigation.preprints',
    icon: 'osf-icon-preprints',
    visible: true,
    routerLinkActiveOptions: { exact: true },
    items: [
      {
        id: 'preprints-overview',
        routerLink: '/preprints/overview',
        label: 'navigation.overview',
        visible: true,
        routerLinkActiveOptions: { exact: false },
      },
      {
        id: 'preprints-moderation',
        routerLink: '/preprints/my-reviewing',
        label: 'navigation.moderation',
        visible: false,
        routerLinkActiveOptions: { exact: true },
      },
      {
        id: 'preprints-details',
        label: 'navigation.preprintsSubRoutes.preprintDetails',
        visible: false,
        routerLinkActiveOptions: { exact: true },
        styleClass: 'border-none',
      },
    ],
  },
  {
    id: 'my-profile',
    routerLink: '/my-profile',
    label: 'navigation.profile',
    icon: 'osf-icon-profile',
    visible: false,
    routerLinkActiveOptions: { exact: false },
  },
  {
    id: 'institutions',
    routerLink: '/institutions',
    label: 'navigation.institutions',
    icon: 'osf-icon-institutions',
    visible: true,
    routerLinkActiveOptions: { exact: false },
  },
  {
    id: 'collections',
    label: 'navigation.collections',
    icon: 'osf-icon-collections',
    visible: true,
    routerLinkActiveOptions: { exact: false },
    items: [
      {
        id: 'collections-moderation',
        routerLink: 'moderation',
        label: 'navigation.moderation',
        visible: false,
        routerLinkActiveOptions: { exact: true },
      },
    ],
  },
  {
    id: 'meetings',
    routerLink: '/meetings',
    label: 'navigation.meetings',
    icon: 'osf-icon-meetings',
    visible: true,
    routerLinkActiveOptions: { exact: false },
  },
  {
    id: 'settings',
    label: 'navigation.settings',
    icon: 'osf-icon-settings',
    routerLinkActiveOptions: { exact: true },
    styleClass: 'mt-5',
    visible: false,
    items: [
      {
        id: 'settings-profile-settings',
        routerLink: '/settings/profile-settings',
        label: 'navigation.profileSettings',
        visible: true,
        routerLinkActiveOptions: { exact: true },
      },
      {
        id: 'settings-account-settings',
        routerLink: '/settings/account-settings',
        label: 'navigation.accountSettings',
        visible: true,
        routerLinkActiveOptions: { exact: true },
      },
      {
        id: 'settings-addons',
        routerLink: '/settings/addons',
        label: 'navigation.configureAddonAccounts',
        visible: true,
        routerLinkActiveOptions: { exact: false },
      },
      {
        id: 'settings-notifications',
        routerLink: '/settings/notifications',
        label: 'navigation.notifications',
        visible: true,
        routerLinkActiveOptions: { exact: true },
      },
      {
        id: 'settings-developer-apps',
        routerLink: '/settings/developer-apps',
        label: 'navigation.developerApps',
        visible: true,
        routerLinkActiveOptions: { exact: false },
      },
      {
        id: 'settings-tokens',
        routerLink: '/settings/tokens',
        label: 'navigation.personalAccessTokens',
        visible: true,
        routerLinkActiveOptions: { exact: false },
      },
    ],
  },
];
