import { SocialLinksModel } from '../models';

export const socials: SocialLinksModel[] = [
  {
    id: 0,
    label: 'ResearcherID',
    address: 'http://researchers.com/rid/',
    placeholder: 'x-xxxx-xxxx',
    key: 'researcherId',
    multiple: false,
  },
  {
    id: 1,
    label: 'ORCID',
    address: 'http://orcid.org/',
    placeholder: 'xxxx-xxxx-xxxx',
    key: 'orcid',
    multiple: false,
  },
  {
    id: 2,
    label: 'LinkedIn',
    address: 'https://linkedin.com/',
    placeholder: 'in/userID, profie/view?profileID, or pub/pubID',
    key: 'linkedIn',
    multiple: true,
  },
  {
    id: 3,
    label: 'X',
    address: '@',
    placeholder: 'twitterhandle',
    key: 'twitter',
    multiple: true,
  },
  {
    id: 4,
    label: 'GitHub',
    address: 'https://github.com/',
    placeholder: 'username',
    key: 'github',
    multiple: true,
  },
  {
    id: 5,
    label: 'ImpactStory',
    address: 'https://impactstory.org/u/',
    placeholder: 'profileID',
    key: 'impactStory',
    multiple: false,
  },
  {
    id: 6,
    label: 'Google Scholar',
    address: 'http://scholar.google.com/citations?user=',
    placeholder: 'profileID',
    key: 'scholar',
    multiple: false,
  },
  {
    id: 7,
    label: 'ResearchGate',
    address: 'https://researchgate.net/profile/',
    placeholder: 'profileID',
    key: 'researchGate',
    multiple: false,
  },
  {
    id: 8,
    label: 'Baidu Scholar',
    address: 'http://xueshu.baidu.com/scholarID/',
    placeholder: 'profileID',
    key: 'baiduScholar',
    multiple: false,
  },
  {
    id: 9,
    label: 'SSRN',
    address: 'http://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=',
    placeholder: 'profileID',
    key: 'ssrn',
    multiple: false,
  },
  {
    id: 10,
    label: 'Your website',
    address: 'website',
    placeholder: 'https://yourwebsite.com',
    key: 'profileWebsites',
    multiple: true,
  },
  {
    id: 11,
    label: 'Academia Profile Id',
    address: '.academia.edu/',
    placeholder: 'profileId',
    key: 'academiaProfileID',
    multiple: false,
  },
];
