import { SocialLinksModel } from '../models';

export const SOCIALS: SocialLinksModel[] = [
  {
    id: 0,
    label: 'settings.profileSettings.social.labels.researcherId',
    address: 'http://researchers.com/rid/',
    placeholder: 'x-xxxx-xxxx',
    key: 'researcherId',
  },
  {
    id: 1,
    label: 'settings.profileSettings.social.labels.orcid',
    address: 'http://orcid.org/',
    placeholder: 'xxxx-xxxx-xxxx',
    key: 'orcid',
  },
  {
    id: 2,
    label: 'settings.profileSettings.social.labels.linkedIn',
    address: 'https://linkedin.com/',
    placeholder: 'in/userID, profie/view?profileID, or pub/pubID',
    key: 'linkedIn',
  },
  {
    id: 3,
    label: 'settings.profileSettings.social.labels.twitter',
    address: '@',
    placeholder: 'twitterhandle',
    key: 'twitter',
  },
  {
    id: 4,
    label: 'settings.profileSettings.social.labels.github',
    address: 'https://github.com/',
    placeholder: 'username',
    key: 'github',
  },
  {
    id: 5,
    label: 'settings.profileSettings.social.labels.impactStory',
    address: 'https://impactstory.org/u/',
    placeholder: 'profileID',
    key: 'impactStory',
  },
  {
    id: 6,
    label: 'settings.profileSettings.social.labels.scholar',
    address: 'http://scholar.google.com/citations?user=',
    placeholder: 'profileID',
    key: 'scholar',
  },
  {
    id: 7,
    label: 'settings.profileSettings.social.labels.researchGate',
    address: 'https://researchgate.net/profile/',
    placeholder: 'profileID',
    key: 'researchGate',
  },
  {
    id: 8,
    label: 'settings.profileSettings.social.labels.baiduScholar',
    address: 'http://xueshu.baidu.com/scholarID/',
    placeholder: 'profileID',
    key: 'baiduScholar',
  },
  {
    id: 9,
    label: 'settings.profileSettings.social.labels.ssrn',
    address: 'http://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=',
    placeholder: 'profileID',
    key: 'ssrn',
  },
  {
    id: 10,
    label: 'settings.profileSettings.social.labels.profileWebsites',
    address: '',
    placeholder: 'https://yourwebsite.com',
    key: 'profileWebsites',
  },
  {
    id: 11,
    label: 'settings.profileSettings.social.labels.academia',
    address: 'https://',
    placeholder: 'institution',
    key: 'academiaInstitution',
    linkedField: {
      key: 'academiaProfileID',
      label: 'settings.profileSettings.social.labels.academiaProfileId',
      placeholder: 'profileId',
    },
  },
];
