name: Run Jest Tests

on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - 'release/*'
      - 'hotfix/*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run ci:test
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests with coverage
        run: npm run ci:test:coverage

      - name: Check coverage thresholds
        run: npm run test:check-coverage-thresholds
      - name: Coveralls Report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Check formatting with prettier
        run: npm run format:check
